### ISSUE TITLE
-Wstringop-truncation warnings observed in core_http_client.c

### ISSUE THREAD

**Issue by SKZahidBasha-Silabs** [FreeRTOS/coreHTTP#133]
![image](https://user-images.githubusercontent.com/88525973/179776014-941934b8-7f10-4156-ae5e-aeb5a7c3c14a.png)

Warnings related to strncpy are observed in the core_http_client.c file at the below lines of code. Attached the warnings snapshot :

**Line 1:** 
       ( void ) strncpy( pBufferCur,
                              HTTP_HEADER_FIELD_SEPARATOR,
                              HTTP_HEADER_FIELD_SEPARATOR_LEN );
                              
**Line 2:**
       ( void ) strncpy( pBufferCur,
                              HTTP_HEADER_END_INDICATOR,
                              HTTP_HEADER_END_INDICATOR_LEN );
                              
**Line 3:**
      ( void ) strncpy( pBufferCur,
                          HTTP_HEADER_LINE_SEPARATOR,
                          HTTP_HEADER_LINE_SEPARATOR_LEN );

**Comment by paulbartell** [comment]
@SKZahidBasha-Silabs : These warnings can be safely ignored since the target buffer is not necessarily a null terminated string.

You can mask these warnings locally with something like:
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstringop-truncation"
strncpy( ... )
#pragma GCC diagnostic pop

**Comment by alfred2g** [comment]
@paulbartell, would be better if we use memcpy instead (since not null terminated) ?

**Comment by RichardBarry** [comment]
To help decide on the action to take - the code needs to compile without warnings with the -Wall and -Wextra GCC command line options.

**Comment by SKZahidBasha-Silabs** [comment]
Is it better to change **strncpy()** to **memcpy()** (or) use the pragmas as suggested above?

**Comment by SKZahidBasha-Silabs** [comment]
@alfred2g / @paulbartell / @RichardBarry so the fix for this would be to convert **strncpy** to **memcpy**, is that right? Shall we conclude on the fix approach please?

**Comment by alfred2g** [comment]
@SKZahidBasha-Silabs, yeah that should be the fix, do you want to push a pull request, or you prefer if we do it ?

**Comment by SKZahidBasha-Silabs** [comment]
@alfred2g  I guess you pushing the fix would be nicer for future tracking. Thanks for the confirmation on approach!

**Comment by alfred2g** [comment]
https://github.com/FreeRTOS/coreHTTP/pull/134

**Comment by alfred2g** [comment]
Code is merged, closing the issue

**Comment by SKZahidBasha-Silabs** [comment]
Thanks, @alfred2g for fixing this!
