### ISSUE TITLE
-Wstringop-truncation warnings observed in core_http_client.c

### ISSUE THREAD

**Issue by SKZahidBasha-Silabs** [FreeRTOS/coreHTTP#137]
Warning related to strncpy is observed in the core_http_client.c file at the below line of code. Attached is the warning snapshot :
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/88525973/184297525-8c4dc0bf-4936-484f-ba57-3cd8bd75c2c2.png)

**Line of code:**

( void ) strncpy( rangeValueBuffer,
                      HTTP_RANGE_REQUEST_HEADER_VALUE_PREFIX,
                      HTTP_RANGE_REQUEST_HEADER_VALUE_PREFIX_LEN );

Note: A similar issue was created in the past for which "strncpy" was replaced with "memcpy" as a fix. Attaching the link to that issue below.
https://github.com/FreeRTOS/coreHTTP/issues/133

**Comment by n9wxu** [comment]
resolved.  But the fix triggers a MISRA rule 7.4 violation.  We will be looking at further changes in the future.
