### ISSUE TITLE
Handling of "Upgrade:" header

### ISSUE THREAD

**Issue by pjanco** [FreeRTOS/coreHTTP#158]
Hi,
I am working on small websocket library that is using transport_interface layer and coreHTTP library for initial handshaking.

"Upgrade:" header in HTTP response ends with error code from function HTTPClient_Send.

I made my fix in file core_http_client.c on line 1206:

if(llhttp_execute( &( pParsingContext->llhttpParser ), parsingStartLoc, parseLen ) == HPE_PAUSED_UPGRADE)
    llhttp_resume_after_upgrade(&( pParsingContext->llhttpParser ));

Regards,
Peter.

**Comment by tony-josi-aws** [comment]
Thanks @pjanco for raising this issue. We will look into this and get back to you, would you be also interested in contributing this change as a pull request so that it will be easier to review and run the CI/CD tests against your changes?

Regards,
Tony

**Comment by tony-josi-aws** [comment]
Closing this as the mentioned PR #159 , fixes this.
