### ISSUE TITLE
httpParserOnStatusCallback() is not called

### ISSUE THREAD

**Issue by TakCodeIT** [FreeRTOS/coreHTTP#171]
httpParserOnStatusCallback() is not called if a server returns a status code without a reason string such as following.

```
HTTP/1.1 400
Server: nginx
Date: Fri, 05 Jan 2024 05:25:21 GMT
Content-Type: application/json
Content-Length: 30
Connection: keep-alive
・・・
```

If a server returns "HTTP/1.1 400 Bad Request" instead of "HTTP/1.1 400", httpParserOnStatusCallback() is called.

**Comment by aggarg** [comment]
It seems that [the underlying parser ](https://github.com/nodejs/llhttp) does not invoke `on_status` callback in this specific case. It still invokes `on_status_complete` callback though. Would you please try the patch below and let me know if it fixes your issue? 

[status.patch](https://github.com/FreeRTOS/coreHTTP/files/13877638/status.patch)

**Comment by aggarg** [comment]
@TakCodeIT Also, can you share which server returns this response?

**Comment by TakCodeIT** [comment]
> It seems that [the underlying parser ](https://github.com/nodejs/llhttp) does not invoke `on_status` callback in this specific case. It still invokes `on_status_complete` callback though. Would you please try the patch below and let me know if it fixes your issue?
> 
> [status.patch](https://github.com/FreeRTOS/coreHTTP/files/13877638/status.patch)

Thank you for the patch. It works!

**Comment by TakCodeIT** [comment]
> @TakCodeIT Also, can you share which server returns this response?

@aggarg Apparently, Tomcat is used for the server.

**Comment by aggarg** [comment]
Fix has been merged in this PR - https://github.com/FreeRTOS/coreHTTP/pull/173. Closing this issue.
