### ISSUE TITLE
cmake file not found

### ISSUE THREAD

**Issue by lpbittoo** [FreeRTOS/coreHTTP#99]
cmake -S test -B build -DBUILD_CLONE_SUBMODULES=ON
CMake Error: The source directory "/home/jaiprakash/Desktop/coreHTTP/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by yourslab** [comment]
Are you certain you are running `cmake -S test -B build -DBUILD_CLONE_SUBMODULES=ON` from the `/home/jaiprakash/Desktop/coreHTTP` directory? I noticed you are correctly passing the `-S test` flag, but it is giving you an error based on the `build` directory.

**Comment by yourslab** [comment]
Hi @lpbittoo. Just wanted to follow up to see if you have been able to resolve this issue.

**Comment by yourslab** [comment]
I'm assuming this has been resolved. Please feel free to open another issue if you are still facing problems.
